### ISSUE TITLE
what is the meta_tags.csv like? 

### ISSUE THREAD

**Issue by yustaub** [nrupatunga/goturn-pytorch#1]
in the demo_folder.py line 106 `tags_csv=model_dir.joinpath('meta_tags.csv')` ,can u describe the meta_tag,csv like? very appreciate for your reply!

**Comment by yustaub** [comment]
when I run this step, 
```
model = GoturnTrain.load_from_metrics(weights_path=ckpt_path,
                                              tags_csv=model_dir.joinpath('meta_tags.csv'))
```
error happens,AttributeError:'Namespace' object has no atttribute 'seed'

**Comment by nrupatunga** [comment]
Hi `meta_tags.csv` holds the params for PyTorch-lightning. 
Once you download the model, you model directory in `demo_folder.sh`
set the path accordingly here
`MODEL_DIR='../../models/caffenet/lightning_logs/version_0/'`

**Comment by nrupatunga** [comment]
**Update**: I have removed the dependency on the `meta_tags.csv`. 
Please use the latest `demo_folder.py`, let me know how it goes.

**Comment by nrupatunga** [comment]
Please feel free to reopen, if you find any issues.

**Comment by yustaub** [comment]
sorry to bother you again! I can run the demo_folder.py now,but the image appear, and I use the mouse draw the bbox, when I press  's', there no thing happen,it just stop there

**Comment by yustaub** [comment]
@nrupatunga

**Comment by nrupatunga** [comment]
Sometimes, I have seen that happening sometimes. Please select the window and press 's' again. it should work. I shall try to fix that.

**Comment by yustaub** [comment]
ok,thank you!very appreciate!
