### ISSUE TITLE
CaffeNet weights 

### ISSUE THREAD

**Issue by erdnag** [nrupatunga/goturn-pytorch#11]
Hi! Thank you for your code! I want to try to modify the network, but it won't let me because of the saved weights in "caffenet_weights.npy". Is there an instruction like in torch.load(strict=False) for npy file or can you tell me what should I do about it? I tried training it without using any pretrained weights and it's not ok.  Sorry if it's an unappropriate question, I am new in this field. Thank you!

**Comment by nrupatunga** [comment]
@erdnag , you should be able to use the backbone architecture of your interest, by modifying this part of the code, 

The model you use if pretrained on any large dataset like Imagenet should be a good start. 

https://github.com/nrupatunga/goturn-pytorch/blob/bb3b3b418ac361aa5782b0a7569cc2191b1c30fc/src/goturn/network/network.py#L35

Let me know if you still face issues.

**Comment by erdnag** [comment]
So if I don't use a pretrained model, it should still learn, but better results will be seen after more epochs? I was just trying to make 4 conv insted of 5 in CaffeNet, not using VGG or resnet which are already pretrained.

**Comment by nrupatunga** [comment]
You still need a pretrained model. it serves as a good init for fine-tuning the model on our task (object tracking)
