### ISSUE TITLE
Multiple Object Tracking

### ISSUE THREAD

**Issue by bayraktare** [nrupatunga/goturn-pytorch#3]
Hi, thanks for this great effort.

I just wonder if we can use this code to track multiple objects in multiple classes (not only vehicles or pedestrians but also other class labels) in a sequence of frames?
In addition, from which exact place we can arrange this code to train on our custom dataset? And what should be the file format for this, how do we feed the bounding boxes, images, etc?

Thanks again for your help...

**Comment by nrupatunga** [comment]
No, it doesn't support multiple object tracking now. 

For training on your custom dataset, you can refer here. 

https://github.com/nrupatunga/goturn-pytorch/issues/2#issuecomment-609405851

**Comment by nrupatunga** [comment]
In order to understand the current working of the data loaders, you can use a smaller dataset to understand it, which you can download it [here](https://drive.google.com/file/d/1XZa4kpgIwUqmrl9vonQZMIaemSUm5P-4/view?usp=sharing)
